version: '3.1'

networks:
  ship_sticks_network:
    external: true

services:
  db:
    image: mongo:4.2
    container_name: ship_sticks-db
    networks:
      - ship_sticks_network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: A9XO#cy!!7cG
      MONGO_INITDB_DATABASE: ship_sticks_development
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  api:
    build: ./backend
    container_name: ship_sticks-api
    networks:
      - ship_sticks_network
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/ship_sticks
    ports:
      - "3001:3000"
    depends_on:
      - db
  frontend:
    image: node:16-alpine
    container_name: ship_sticks-frontend
    networks:
      - ship_sticks_network
    user: "node"
    working_dir: /myapp/frontend
    volumes:
      - ./frontend:/myapp/frontend
    command: "yarn start"
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db-data:
